# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
  First make sure you've installed pull panda on slack and github -- https://pullreminders.com/
  Then please make sure to thoroughly read our contributing guidelines found here -- https://vi.tech.nyt.net/
  Happy coding! :)
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! We here at the New York Times are proud of you!
  Please make sure to inform the appropriate stakeholders about your merge, and keep a look out on drone regarding your build.
  If you'd like to make a release after merge look here for instructions -- https://vi.tech.nyt.net/processes/deploy/
